; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 6
; Issue #58397: switch-ABI coroutine frame must place the promise at the
; ABI-required offset of 2*ptrsize from the handle, regardless of the
; promise's natural alignment.
; Three variants:
;   - align 16 (== 2*ptrsize on x86_64):  no padding, no GEP, baseline.
;   - align 32 (== 4*ptrsize):             padding = 16 bytes.
;   - align 64 (cache-line):               padding = 48 bytes.
; Things we check (per variant):
;   - ramp:    malloc size accounts for the padding,
;              frame_ptr = alloc + padding (omitted when padding == 0),
;              promise stored via memcpy at frame_ptr + 16 (= 2*ptrsize).
;   - resume:  promise reload at frame_ptr + 16 (NOT alignTo(16, alignof)).
;              degraded `align` / `dereferenceable` on the frame_ptr param.
;   - cleanup: free uses (frame_ptr - padding), null-preserving select so
;              the no-suspend / heap-elision paths still work correctly.
; RUN: opt < %s -passes='cgscc(coro-split),simplifycfg,early-cse' -S \
; RUN:   | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%align16 = type { [16 x i8] }
%align32 = type { [32 x i8] }
%align64 = type { [64 x i8] }

declare void @use(ptr)
declare ptr @llvm.coro.free(token, ptr)
declare i32 @llvm.coro.size.i32()
declare i32 @llvm.coro.align.i32()
declare i8  @llvm.coro.suspend(token, i1)
declare token @llvm.coro.id(i32, ptr, ptr, ptr)
declare i1   @llvm.coro.alloc(token)
declare ptr  @llvm.coro.begin(token, ptr)
declare void @llvm.coro.end(ptr, i1, token)
declare noalias ptr @malloc(i32)
declare void @free(ptr)

define ptr @f_align16() presplitcoroutine {
entry:
  %p = alloca %align16, align 16
  %id = call token @llvm.coro.id(i32 0, ptr %p, ptr @f_align16, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %mem = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %mem)
  call void @use(ptr %p)
  %s = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %s, label %suspend [i8 0, label %resume i8 1, label %cleanup]
resume:
  call void @use(ptr %p)
  br label %cleanup
cleanup:
  %dealloc = call ptr @llvm.coro.free(token %id, ptr %hdl)
  call void @free(ptr %dealloc)
  br label %suspend
suspend:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret ptr %hdl
}

define ptr @f_align32() presplitcoroutine {
entry:
  %p = alloca %align32, align 32
  %id = call token @llvm.coro.id(i32 0, ptr %p, ptr @f_align32, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %mem = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %mem)
  call void @use(ptr %p)
  %s = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %s, label %suspend [i8 0, label %resume i8 1, label %cleanup]
resume:
  call void @use(ptr %p)
  br label %cleanup
cleanup:
  %dealloc = call ptr @llvm.coro.free(token %id, ptr %hdl)
  call void @free(ptr %dealloc)
  br label %suspend
suspend:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret ptr %hdl
}

define ptr @f_align64() presplitcoroutine {
entry:
  %p = alloca %align64, align 64
  %id = call token @llvm.coro.id(i32 0, ptr %p, ptr @f_align64, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %mem = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %mem)
  call void @use(ptr %p)
  %s = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %s, label %suspend [i8 0, label %resume i8 1, label %cleanup]
resume:
  call void @use(ptr %p)
  br label %cleanup
cleanup:
  %dealloc = call ptr @llvm.coro.free(token %id, ptr %hdl)
  call void @free(ptr %dealloc)
  br label %suspend
suspend:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret ptr %hdl
}
; CHECK-LABEL: define ptr @f_align16() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f_align16, ptr @f_align16.resumers)
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @malloc(i32 48)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[MEM]])
; CHECK-NEXT:    store ptr @f_align16.resume, ptr [[HDL]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 8
; CHECK-NEXT:    store ptr @f_align16.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    [[P_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    call void @use(ptr [[P_RELOAD_ADDR]])
; CHECK-NEXT:    [[INDEX_ADDR1:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 32
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR1]], align 1
; CHECK-NEXT:    ret ptr [[HDL]]
;
;
; CHECK-LABEL: define ptr @f_align32() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f_align32, ptr @f_align32.resumers)
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @malloc(i32 96)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[MEM]])
; CHECK-NEXT:    [[FRAME_PTR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    store ptr @f_align32.resume, ptr [[FRAME_PTR]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 8
; CHECK-NEXT:    store ptr @f_align32.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    [[P_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 16
; CHECK-NEXT:    call void @use(ptr [[P_RELOAD_ADDR]])
; CHECK-NEXT:    [[INDEX_ADDR1:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 48
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR1]], align 1
; CHECK-NEXT:    ret ptr [[FRAME_PTR]]
;
;
; CHECK-LABEL: define ptr @f_align64() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f_align64, ptr @f_align64.resumers)
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @malloc(i32 192)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[MEM]])
; CHECK-NEXT:    [[FRAME_PTR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 48
; CHECK-NEXT:    store ptr @f_align64.resume, ptr [[FRAME_PTR]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 8
; CHECK-NEXT:    store ptr @f_align64.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    [[P_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 16
; CHECK-NEXT:    call void @use(ptr [[P_RELOAD_ADDR]])
; CHECK-NEXT:    [[INDEX_ADDR1:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 80
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR1]], align 1
; CHECK-NEXT:    ret ptr [[FRAME_PTR]]
;
;
; CHECK-LABEL: define internal void @f_align16.resume(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(48) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_RESUME:.*:]]
; CHECK-NEXT:    [[P_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 16
; CHECK-NEXT:    call void @use(ptr [[P_RELOAD_ADDR]])
; CHECK-NEXT:    [[DEALLOC:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[HDL]])
; CHECK-NEXT:    call void @free(ptr [[DEALLOC]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align16.destroy(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(48) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_DESTROY:.*:]]
; CHECK-NEXT:    [[DEALLOC:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[HDL]])
; CHECK-NEXT:    call void @free(ptr [[DEALLOC]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align16.cleanup(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(48) [[HDL:%.*]]) {
; CHECK-NEXT:  [[ENTRY_CLEANUP:.*:]]
; CHECK-NEXT:    call void @free(ptr null)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align32.resume(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(80) "coro-frame-align"="32" "coro-frame-size"="96" [[FRAME_PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY_RESUME:.*:]]
; CHECK-NEXT:    [[P_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 16
; CHECK-NEXT:    call void @use(ptr [[P_RELOAD_ADDR]])
; CHECK-NEXT:    [[DEALLOC:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[FRAME_PTR]])
; CHECK-NEXT:    [[ALLOC_PTR_ISNULL:%.*]] = icmp eq ptr [[DEALLOC]], null
; CHECK-NEXT:    [[ALLOC_PTR_NONNULL:%.*]] = getelementptr inbounds i8, ptr [[DEALLOC]], i64 -16
; CHECK-NEXT:    [[ALLOC_PTR:%.*]] = select i1 [[ALLOC_PTR_ISNULL]], ptr null, ptr [[ALLOC_PTR_NONNULL]]
; CHECK-NEXT:    call void @free(ptr [[ALLOC_PTR]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align32.destroy(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(80) "coro-frame-align"="32" "coro-frame-size"="96" [[FRAME_PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY_DESTROY:.*:]]
; CHECK-NEXT:    [[DEALLOC:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[FRAME_PTR]])
; CHECK-NEXT:    [[ALLOC_PTR_ISNULL:%.*]] = icmp eq ptr [[DEALLOC]], null
; CHECK-NEXT:    [[ALLOC_PTR_NONNULL:%.*]] = getelementptr inbounds i8, ptr [[DEALLOC]], i64 -16
; CHECK-NEXT:    [[ALLOC_PTR:%.*]] = select i1 [[ALLOC_PTR_ISNULL]], ptr null, ptr [[ALLOC_PTR_NONNULL]]
; CHECK-NEXT:    call void @free(ptr [[ALLOC_PTR]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align32.cleanup(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(80) "coro-frame-align"="32" "coro-frame-size"="96" [[FRAME_PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY_CLEANUP:.*:]]
; CHECK-NEXT:    call void @free(ptr null)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align64.resume(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(144) "coro-frame-align"="64" "coro-frame-size"="192" [[FRAME_PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY_RESUME:.*:]]
; CHECK-NEXT:    [[P_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 16
; CHECK-NEXT:    call void @use(ptr [[P_RELOAD_ADDR]])
; CHECK-NEXT:    [[DEALLOC:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[FRAME_PTR]])
; CHECK-NEXT:    [[ALLOC_PTR_ISNULL:%.*]] = icmp eq ptr [[DEALLOC]], null
; CHECK-NEXT:    [[ALLOC_PTR_NONNULL:%.*]] = getelementptr inbounds i8, ptr [[DEALLOC]], i64 -48
; CHECK-NEXT:    [[ALLOC_PTR:%.*]] = select i1 [[ALLOC_PTR_ISNULL]], ptr null, ptr [[ALLOC_PTR_NONNULL]]
; CHECK-NEXT:    call void @free(ptr [[ALLOC_PTR]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align64.destroy(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(144) "coro-frame-align"="64" "coro-frame-size"="192" [[FRAME_PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY_DESTROY:.*:]]
; CHECK-NEXT:    [[DEALLOC:%.*]] = call ptr @llvm.coro.free(token poison, ptr [[FRAME_PTR]])
; CHECK-NEXT:    [[ALLOC_PTR_ISNULL:%.*]] = icmp eq ptr [[DEALLOC]], null
; CHECK-NEXT:    [[ALLOC_PTR_NONNULL:%.*]] = getelementptr inbounds i8, ptr [[DEALLOC]], i64 -48
; CHECK-NEXT:    [[ALLOC_PTR:%.*]] = select i1 [[ALLOC_PTR_ISNULL]], ptr null, ptr [[ALLOC_PTR_NONNULL]]
; CHECK-NEXT:    call void @free(ptr [[ALLOC_PTR]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @f_align64.cleanup(
; CHECK-SAME: ptr noundef nonnull align 16 dereferenceable(144) "coro-frame-align"="64" "coro-frame-size"="192" [[FRAME_PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY_CLEANUP:.*:]]
; CHECK-NEXT:    call void @free(ptr null)
; CHECK-NEXT:    ret void
;
