; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Regression test for the BUG-4 hazard found during code review of the
; issue #58397 fix: with an over-aligned promise the prefix field is
; field index 0 at offset 0 in the FrameTypeBuilder layout. Zero-size
; spills / allocas (e.g. SROA leftovers, `alloca {}`) are also mapped to
; field index 0 by `FrameTypeBuilder::addField` (it short-circuits on
; `FieldSize == 0`), so they would naively translate to
; `Offset - HandleOffset == -HandleOffset`, asserting in debug builds and
; underflowing in release. `FrameDataInfo::updateLayoutInfo` now keeps
; zero-size fields at offset 0 (their address is unobservable).
;
; RUN: opt < %s -passes='cgscc(coro-split),simplifycfg,early-cse' -S \
; RUN:   | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%align64 = type { [64 x i8] }
%empty = type { }

declare void @use(ptr)
declare void @use_empty(ptr)
declare ptr @llvm.coro.free(token, ptr)
declare i32 @llvm.coro.size.i32()
declare i8  @llvm.coro.suspend(token, i1)
declare token @llvm.coro.id(i32, ptr, ptr, ptr)
declare ptr  @llvm.coro.begin(token, ptr)
declare void @llvm.coro.end(ptr, i1, token)
declare noalias ptr @malloc(i32)
declare void @free(ptr)

define ptr @f_zero_size() presplitcoroutine {
; CHECK-LABEL: define ptr @f_zero_size() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ID:%.*]] = call token @llvm.coro.id(i32 0, ptr null, ptr @f_zero_size, ptr @f_zero_size.resumers)
; CHECK-NEXT:    [[MEM:%.*]] = call ptr @malloc(i32 192)
; CHECK-NEXT:    [[HDL:%.*]] = call noalias nonnull ptr @llvm.coro.begin(token [[ID]], ptr [[MEM]])
; CHECK-NEXT:    [[FRAME_PTR:%.*]] = getelementptr inbounds i8, ptr [[HDL]], i64 48
; CHECK-NEXT:    store ptr @f_zero_size.resume, ptr [[FRAME_PTR]], align 8
; CHECK-NEXT:    [[DESTROY_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 8
; CHECK-NEXT:    store ptr @f_zero_size.destroy, ptr [[DESTROY_ADDR]], align 8
; CHECK-NEXT:    [[P_RELOAD_ADDR:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 16
; CHECK-NEXT:    call void @use(ptr [[P_RELOAD_ADDR]])
; CHECK-NEXT:    call void @use_empty(ptr [[FRAME_PTR]])
; CHECK-NEXT:    [[INDEX_ADDR1:%.*]] = getelementptr inbounds i8, ptr [[FRAME_PTR]], i64 80
; CHECK-NEXT:    store i1 false, ptr [[INDEX_ADDR1]], align 1
; CHECK-NEXT:    ret ptr [[FRAME_PTR]]
;
entry:
  %p = alloca %align64, align 64
  %e = alloca %empty, align 1
  %id = call token @llvm.coro.id(i32 0, ptr %p, ptr @f_zero_size, ptr null)
  %size = call i32 @llvm.coro.size.i32()
  %mem = call ptr @malloc(i32 %size)
  %hdl = call ptr @llvm.coro.begin(token %id, ptr %mem)
  call void @use(ptr %p)
  call void @use_empty(ptr %e)
  %s = call i8 @llvm.coro.suspend(token none, i1 false)
  switch i8 %s, label %suspend [i8 0, label %resume i8 1, label %cleanup]
resume:
  call void @use(ptr %p)
  call void @use_empty(ptr %e)
  br label %cleanup
cleanup:
  %dealloc = call ptr @llvm.coro.free(token %id, ptr %hdl)
  call void @free(ptr %dealloc)
  br label %suspend
suspend:
  call void @llvm.coro.end(ptr %hdl, i1 0, token none)
  ret ptr %hdl
}

; Ramp lays out the over-aligned promise at frame_ptr + 16. The empty
; alloca's reload offset must be 0 (handle-relative) and not a wrap-around
; like `i64 -48` that would point inside the padding prefix.
;
; The resume function loads %p at +16. The %e load (if any) must not GEP
; *backwards* off frame_ptr — that would mean BUG-4 silently underflowed.
